### ISSUE TITLE
Docs issues

### ISSUE THREAD

**Issue by hroncok** [Fanarim/github_labelbot#8]
* [ ] The instructions in README about docs building are incomplete:

```
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
make: sphinx-build: Command not found
Makefile:53: recipe for target 'html' failed
make: *** [html] Error 127
$ pip install sphinx # I'm guessing here
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.8
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: 6 added, 0 changed, 0 removed
reading sources... [100%] source-documentation                                                                                                                                                                                     
docs/source-documentation.rst:12: WARNING: autodoc: failed to import module 'github_labelbot.labelbot'; the following exception was raised:
Traceback (most recent call last):
  File "env/lib64/python3.5/site-packages/sphinx/ext/autodoc.py", line 519, in import_object
    __import__(self.modname)
  File "github_labelbot/labelbot.py", line 5, in <module>
    import appdirs
ImportError: No module named 'appdirs'
docs/source-documentation.rst:20: WARNING: autodoc: failed to import module 'github_labelbot.run'; the following exception was raised:
Traceback (most recent call last):
  File "env/lib64/python3.5/site-packages/sphinx/ext/autodoc.py", line 519, in import_object
    __import__(self.modname)
  File "github_labelbot/run.py", line 3, in <module>
    import appdirs
ImportError: No module named 'appdirs'
docs/source-documentation.rst:28: WARNING: autodoc: failed to import module 'github_labelbot.web'; the following exception was raised:
Traceback (most recent call last):
  File "env/lib64/python3.5/site-packages/sphinx/ext/autodoc.py", line 519, in import_object
    __import__(self.modname)
  File "github_labelbot/web.py", line 1, in <module>
    from flask import abort
ImportError: No module named 'flask'
...
```

* [ ] No doctest
* [ ] No Travis CI
* [ ] Incomplete API docs on Read the Docs

**Comment by viktoradavid** [comment]
Thanks for the issue, no resources to fix this rn.
